package com.lst.lc.entities;

// Generated 2015-7-18 14:55:52 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Operation generated by hbm2java
 */
@Entity
@Table(name = "operation", catalog = "LearningCommunity")
public class Operation implements java.io.Serializable {

	private Integer operationId;
	private String operation;
	private int integral;

	public Operation() {
	}

	public Operation(String operation, int integral) {
		this.operation = operation;
		this.integral = integral;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "operationId", unique = true, nullable = false)
	public Integer getOperationId() {
		return this.operationId;
	}

	public void setOperationId(Integer operationId) {
		this.operationId = operationId;
	}

	@Column(name = "operation", nullable = false, length = 200)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "integral", nullable = false)
	public int getIntegral() {
		return this.integral;
	}

	public void setIntegral(int integral) {
		this.integral = integral;
	}

}
