package com.lst.lc.entities;

// Generated 2015-7-18 14:50:41 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Operation generated by hbm2java
 */
@Entity
@Table(name = "operation", catalog = "LearningCommunity")
public class Operation implements java.io.Serializable {

	private String operaiton;
	private int integral;

	public Operation() {
	}

	public Operation(String operaiton, int integral) {
		this.operaiton = operaiton;
		this.integral = integral;
	}

	@Id
	@Column(name = "operaiton", unique = true, nullable = false, length = 200)
	public String getOperaiton() {
		return this.operaiton;
	}

	public void setOperaiton(String operaiton) {
		this.operaiton = operaiton;
	}

	@Column(name = "integral", nullable = false)
	public int getIntegral() {
		return this.integral;
	}

	public void setIntegral(int integral) {
		this.integral = integral;
	}

}
