package com.lst.lc.entities;

// Generated 2015-7-18 14:55:52 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rank generated by hbm2java
 */
@Entity
@Table(name = "rank", catalog = "LearningCommunity")
public class Rank implements java.io.Serializable {

	private Integer rankId;
	private String rankName;
	private int integral;

	public Rank() {
	}

	public Rank(String rankName, int integral) {
		this.rankName = rankName;
		this.integral = integral;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "rankId", unique = true, nullable = false)
	public Integer getRankId() {
		return this.rankId;
	}

	public void setRankId(Integer rankId) {
		this.rankId = rankId;
	}

	@Column(name = "rankName", nullable = false, length = 50)
	public String getRankName() {
		return this.rankName;
	}

	public void setRankName(String rankName) {
		this.rankName = rankName;
	}

	@Column(name = "integral", nullable = false)
	public int getIntegral() {
		return this.integral;
	}

	public void setIntegral(int integral) {
		this.integral = integral;
	}

}
