package com.lst.lc.entities;

// Generated 2015-7-18 9:37:36 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RelUserCourseId generated by hbm2java
 */
@Embeddable
public class RelUserCourseId implements java.io.Serializable {

	private int userId;
	private int courseId;

	public RelUserCourseId() {
	}

	public RelUserCourseId(int userId, int courseId) {
		this.userId = userId;
		this.courseId = courseId;
	}

	@Column(name = "userId", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "courseId", nullable = false)
	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelUserCourseId))
			return false;
		RelUserCourseId castOther = (RelUserCourseId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getCourseId() == castOther.getCourseId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getCourseId();
		return result;
	}

}
