package com.lst.lc.entities;

// Generated 2015-7-17 15:14:15 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StudyRoute generated by hbm2java
 */
@Entity
@Table(name = "studyRoute", catalog = "LearningCommunity")
public class StudyRoute implements java.io.Serializable {

	private Integer routeId;
	private String name;
	private String description;
	private String tag;
	private int courseNums;
	private int studentNums;
	private String imageUrl;
	private Set<RelCourseRoute> relCourseRoutes = new HashSet<RelCourseRoute>(0);
	private Set<RelUserRoute> relUserRoutes = new HashSet<RelUserRoute>(0);

	public StudyRoute() {
	}

	public StudyRoute(String name, String description, String tag,
			int courseNums, int studentNums, String imageUrl) {
		this.name = name;
		this.description = description;
		this.tag = tag;
		this.courseNums = courseNums;
		this.studentNums = studentNums;
		this.imageUrl = imageUrl;
	}

	public StudyRoute(String name, String description, String tag,
			int courseNums, int studentNums, String imageUrl,
			Set<RelCourseRoute> relCourseRoutes, Set<RelUserRoute> relUserRoutes) {
		this.name = name;
		this.description = description;
		this.tag = tag;
		this.courseNums = courseNums;
		this.studentNums = studentNums;
		this.imageUrl = imageUrl;
		this.relCourseRoutes = relCourseRoutes;
		this.relUserRoutes = relUserRoutes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "routeId", unique = true, nullable = false)
	public Integer getRouteId() {
		return this.routeId;
	}

	public void setRouteId(Integer routeId) {
		this.routeId = routeId;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "tag", nullable = false, length = 200)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Column(name = "courseNums", nullable = false)
	public int getCourseNums() {
		return this.courseNums;
	}

	public void setCourseNums(int courseNums) {
		this.courseNums = courseNums;
	}

	@Column(name = "studentNums", nullable = false)
	public int getStudentNums() {
		return this.studentNums;
	}

	public void setStudentNums(int studentNums) {
		this.studentNums = studentNums;
	}

	@Column(name = "imageUrl", nullable = false, length = 200)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studyRoute")
	public Set<RelCourseRoute> getRelCourseRoutes() {
		return this.relCourseRoutes;
	}

	public void setRelCourseRoutes(Set<RelCourseRoute> relCourseRoutes) {
		this.relCourseRoutes = relCourseRoutes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studyRoute")
	public Set<RelUserRoute> getRelUserRoutes() {
		return this.relUserRoutes;
	}

	public void setRelUserRoutes(Set<RelUserRoute> relUserRoutes) {
		this.relUserRoutes = relUserRoutes;
	}

}
